# Generated by Django 3.2.14 on 2022-08-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
        ('shop', '0006_auto_20220822_1424'),
        ('cart', '0002_alter_customer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.PositiveIntegerField(verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], max_length=50, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(max_length=200, verbose_name='Ordered by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Payment Completed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
