# Generated by Django 3.2.14 on 2022-08-22 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_admin', '0002_rename_admin_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='image',
            field=models.ImageField(upload_to='admins_img/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='joined_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Joined in'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
